grammar fr.enseeiht.PDLP with org.eclipse.xtext.common.Terminals

generate pDLP "http://www.enseeiht.fr/PDLP"

Process :
	'process' name=ID 
		'[' min_time=INT
		',' max_time=INT
		'] {'
	    	processElements+=ProcessElement*
		'}' ('(' resources+=Resource*')')?
	;

ProcessElement :
	WorkDefinition
	| WorkSequence
	| Guidance
	|Parameter
	;

WorkDefinition :
	'wd' name=ID
		'[' min_time=INT
		',' max_time=INT
		'] (' needs+=Parameter*
		')' 
		('links to predecessors : 'linksToPredecessors+=[WorkSequence]*)?
		('links to successors : 'linksToSuccessors+=[WorkSequence]*)?
	;
	
WorkSequence :
	'ws' (name=ID)?
		linkType=WorkSequenceType
		'from' predecessor=[WorkDefinition]
		'to' successor=[WorkDefinition]
	;
	
Guidance:
	text=STRING
	('to' element+=[ProcessElement])?
	;
	
Parameter:
	'par' name=ID':'nbNeeds = INT
	'of' resource=[Resource]
	('used by' workDefinition=[WorkDefinition])? 
;

Resource:
	'res' name=ID':'marking=INT
;

enum WorkSequenceType :
	start2start = 's2s'
	| finish2start = 'f2s'
	| start2finish = 's2f'
	| finish2finish = 'f2f'
	;